import Head from 'next/head'
import Image from 'next/image'
import styles from '../../../styles/Home.module.css'
import logo from '../../../public/logo.png'
import Button from './../../../components/Button'
import GithubIcon from '../../../components/icons/Github'
import React, { useEffect } from 'react'
import loginWithGithub from '../../../firebase/client'
import { useRouter } from 'next/router'
import BtnStyles from '../../../styles/Buttons.module.css'
import useUser from '../../../hooks/useUser'

export default function Login() {
  const router = useRouter()

  const user = useUser()

  useEffect(() => {
    user && router.replace('/homePage')
  },[user])

  const handleClick = () => {
    loginWithGithub().catch((err) => {
      console.log(err)
    })
  }

  return (
    <div className='appContainer'>
      <Head>
        <title>Create Next App</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>

      <main className={styles.main}>
        <Image
          alt='Devter logo'
          src={logo}
          width={100}
          height={100}
          style={{
            maxWidth: '50%',
            height: 'auto'
          }}
        />
        <h1 className='devterTitle'>Devter</h1>
        <h2>Talk about development with developers 👨‍💻👩‍💻</h2>

        {user === null && (
          <Button onClick={handleClick} className={BtnStyles.githubAuthBtn}>
            <GithubIcon />
            Login with Github
          </Button>
        )}
      </main>
    </div>
  )
}
